name: CI

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

jobs:
  lint:
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint

  tests:
    needs: lint
    name: 'Tests: ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}-latest'

    strategy:
      matrix:
        os: [ubuntu, macOS, windows]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: ember test

  tests_compat:
    needs: lint
    name: 'Tests: Compatibility'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: './node_modules/.bin/ember try:each'
